from abc import ABC, abstractmethod
from simfleet.utils.statistics import Log


# Base class (parent)
class BaseStatisticsClass(ABC):
    """
    Abstract interface for SimFleet statistics processors.

    Statistics processors consume a completed global ``Log`` generated by the
    Simulator after agent events have been aggregated and timestamp-normalized.

    Concrete implementations decide which events are meaningful, calculate
    modality-specific KPIs, and optionally export or print their results.
    """

    @abstractmethod
    def run(self, events_log: Log) -> None:
        """
        Process a completed SimFleet event Log.

        Args:
            events_log (Log): Global event collection produced by the Simulator.

        Raises:
            NotImplementedError: If a subclass does not implement processing.
        """
        raise NotImplementedError("Subclasses must implement the run method.")

    def print_stats(self) -> None:
        """
        Print statistics produced by the concrete processor.

        Subclasses that expose interactive output must override this method.

        Raises:
            NotImplementedError: When no concrete printer is implemented.
        """
        raise NotImplementedError("No statistics are printed because it has not been implemented.")
